### ISSUE TITLE
Control the size of the keyboard

### ISSUE THREAD

**Issue by grburgos** [sdeering/onscreenkeyboard#10]
I was wondering is there a simple way to specify the total size of the keyboard? Kind of a zoom? I'm trying to use the keyboard on a mobile device and it works the problem is that the keyboard is too big. I played with the width and height css but ended up deforming it.

**Comment by sdeering** [comment]
@grburgos this would be difficult as the keyboard was not build entirely for responsiveness. However, will a bit of CSS and some tweaks in the JS it wouldn't be too hard I imagine.

**Comment by grburgos** [comment]
Take a look at my fork of your code.
