### ISSUE TITLE
Symbol Button Is not Accurate

### ISSUE THREAD

**Issue by mmeiers** [sdeering/onscreenkeyboard#13]
The symbol button in the lower right corner has the following characters on it "#$+".

However the dollar sign is not actually under this subset of buttons, it is with the numbers. 
Suggestion: change the button to display "#%+".

Thanks,
Mat

**Comment by sdeering** [comment]
Hi Matt, 
Good point, I didn't even notice that there was no dollar sign in the layout! If developers want to use the local currency symbol in the future they can switch it for the € or £ symbols.
Thanks,
Sam

https://github.com/sdeering/onscreenkeyboard/commit/64b635b390cbc9cbd054d0252940ea4056448d43
